# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180226_1926'),
        ('teams', '0015_auto_20180129_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.Group'),
        ),
    ]
