# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start_ts', models.DateTimeField(db_index=True, verbose_name=b'Request started at')),
                ('end_ts', models.DateTimeField(db_index=True, verbose_name=b'Request ended at')),
                ('duration', models.FloatField(verbose_name=b'Request duration (sec)')),
                ('http_method', models.CharField(max_length=10)),
                ('request_uri', models.URLField(verbose_name=b'Request path')),
                ('request_data_get', models.TextField()),
                ('request_data_post', models.TextField()),
                ('remote_addr', models.CharField(max_length=100)),
                ('view_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('http_user_agent', models.CharField(max_length=400)),
                ('http_referer', models.CharField(default='', max_length=400)),
                ('response_status_code', models.IntegerField(db_index=True)),
                ('record_type', models.CharField(default=b'api', max_length=10)),
                ('response_content_length', models.IntegerField()),
            ],
        ),
    ]
