# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-17 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(b'created', b'created'), (b'accepted', b'accepted'), (b'progress', b'progress'), (b'delivered', b'delivered'), (b'canceled', b'canceled'), (b'deleted', b'deleted')], default=b'created', max_length=16),
        ),
    ]
