# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180617_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_priority',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
