# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_status_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytaskcontent',
            name='address',
            field=models.TextField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverytaskcontent',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverytaskcontent',
            name='order_id',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='deliverytaskcontent',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
