# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180628_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='action_type',
            field=models.CharField(choices=[(b'created', b'created'), (b'assigned', b'assigned'), (b'status', b'status'), (b'content', b'content')], default='', max_length=16),
            preserve_default=False,
        ),
    ]
