# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_team_admin'),
        ('crm', '0004_auto_20180710_0900'),
        ('tasks', '0005_taskhistory_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTaskContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=140)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('items', models.ManyToManyField(to='crm.Item')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taskmedia',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmedia',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='tasks.Task'),
        ),
    ]
