# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-13 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_merchant_local_id'),
        ('tasks', '0007_auto_20180710_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTaskItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Item')),
                ('sales_task_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.SalesTaskContent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='salestaskcontent',
            name='items_temp',
            field=models.ManyToManyField(related_name='items', through='tasks.SalesTaskItems', to='crm.Item'),
        ),
    ]
