# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-13 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180713_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestaskcontent',
            name='items',
        ),
    ]
