# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-13 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_salestaskcontent_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestaskcontent',
            old_name='items_temp',
            new_name='items',
        ),
    ]
