# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-14 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20180713_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='salestaskcontent',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.Merchant'),
        ),
        migrations.AlterField(
            model_name='salestaskitems',
            name='sales_task_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.SalesTaskContent'),
        ),
    ]
