# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_salestaskcontent_sales_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestaskcontent',
            name='sales_type',
            field=models.CharField(blank=True, choices=[(b'buy', b'buy'), (b'sell', b'sell')], max_length=16),
        ),
    ]
