# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20180806_0633'),
        ('tasks', '0014_auto_20180806_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestaskcontent',
            name='merchant_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller', to='crm.Merchant'),
        ),
    ]
