# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
