# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180710_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_lower',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='name_lower',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
