# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180710_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
