# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_merchantupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantupload',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
