# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 12:21
from __future__ import unicode_literals

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0020_team_admin'),
        ('crm', '0006_merchantupload_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(b'created', b'created'), (b'progress', b'progress'), (b'success', b'success'), (b'failed', b'failed')], default=b'created', max_length=16)),
                ('data', models.FileField(upload_to=crm.models.upload_item_csv_path)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
