# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_itemupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='local_id',
            field=models.CharField(blank=True, default=b'', max_length=16),
        ),
    ]
