# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-26 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_merchant_local_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_type',
            field=models.CharField(blank=True, choices=[(b'retail', b'retail'), (b'wholesale', b'wholesale')], max_length=16),
        ),
        migrations.AddField(
            model_name='merchant',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
