# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-28 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20180728_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='composition',
            new_name='description',
        ),
    ]
