# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-02 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20180728_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemupload',
            name='status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'progress', b'progress'), (b'success', b'success'), (b'failed', b'failed')], default=b'pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='merchantupload',
            name='status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'progress', b'progress'), (b'success', b'success'), (b'failed', b'failed')], default=b'pending', max_length=16),
        ),
    ]
