# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0008_useranalyzedlocation_userstoplocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranalyzedlocation',
            unique_together=set([('user', 'date')]),
        ),
    ]
