# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-06 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20180331_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstatus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonestatus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useranalyzedlocation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstoplocation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
