# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 10, 45, 55, 863798, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
